### ISSUE TITLE
Removal from Ansible (Community package requirements: sanity tests)

### ISSUE THREAD

**Issue by gotmax23** [cyberark/ansible-conjur-collection#201]
(Note: This issue was filed in a semi-automated fashion. Let me know if you see errors in this issue.)

As per the [Ansible community package inclusion requirements][ci-testing], collections must pass `ansible-test sanity` tests. Version `1.2.2` of `cyberark.conjur`, corresponding to the `v1.2.2` tag in this repo, fails one or more of the required sanity tests.

Please see the errors below and address them. If these issues aren't addressed within a reasonable time period, the collection may be subject to [removal from Ansible][removal].

Thank you for your efforts and for being part of the Ansible package! We appreciate it.

---

## Sanity tests

The following tests were run using `ansible-test` version `2.16.1`:

- ansible-doc
- compile
- validate-modules
- yamllint

Note that this is only a subset of the required sanity tests. Please make sure you run them in all in your CI.

### Results

> **💡 NOTE:**
>
> Check the `[explain]` links below for more information about each test and how to fix failures.
> See [Sanity Tests: Ignores](https://docs.ansible.com/ansible/latest/dev_guide/testing/sanity/ignores.html) in the dev guide if, after reading the test-specific documentation, you still believe an error is a false positive.

The test `ansible-test sanity --test validate-modules` [[explain](https://docs.ansible.com/ansible-core/2.16/dev_guide/testing/sanity/validate-modules.html)] failed with 1 error:

``` text
plugins/lookup/conjur_variable.py:0:0: version-added-must-be-major-or-minor: DOCUMENTATION: version_added ('1.0.2') must be a major or minor release, not a patch release (see specification at https://semver.org/). Got {'name': 'conjur_variable', 'version_added': '1.0.2', 'short_description': 'Fetch credentials from CyberArk Conjur.', 'author': ['CyberArk BizDev (@cyberark-bizdev)'], 'description': "Retrieves credentials from Conjur using the controlling host's Conjur identity or environment variables. Environment variables could be CONJUR_ACCOUNT, CONJUR_APPLIANCE_URL, CONJUR_CERT_FILE, CONJUR_AUTHN_LOGIN, CONJUR_AUTHN_API_KEY, CONJUR_AUTHN_TOKEN_FILE Conjur info - U(https://www.conjur.org/).", 'requiremen...
```

The test `ansible-test sanity --test yamllint` [[explain](https://docs.ansible.com/ansible-core/2.16/dev_guide/testing/sanity/yamllint.html)] failed with 2 errors:

``` text
dev/policy/root.yml:2:3: unparsable-with-libyaml: None - could not determine a constructor for the tag '!policy'
secrets.yml:2:17: unparsable-with-libyaml: None - could not determine a constructor for the tag '!var'
```

[ci-testing]: https://docs.ansible.com/ansible/latest/community/collection_contributors/collection_requirements.html#ci-testing
[repo-mgmt]: https://docs.ansible.com/ansible/latest/community/collection_contributors/collection_requirements.html#repository-management
[removal]: https://github.com/ansible-collections/overview/blob/main/removal_from_ansible.rst

**Comment by gotmax23** [comment]
Please take a look at the outstanding sanity test errors. https://github.com/ansible-community/package-test-results/blob/main/rendered/10.3.0/cyberark.pas.md contains the results for the latest version of ansible. Note that, if these issues aren't acknowledged within a reasonable time period, the collection may be subject to [removal from Ansible](https://github.com/ansible-collections/overview/blob/main/removal_from_ansible.rst).

**Comment by gotmax23** [comment]
Please also make sure that you are running the required CI tests in this repository as explained in https://docs.ansible.com/ansible/devel/community/collection_contributors/collection_requirements.html#ci-testing. It looks like https://github.com/cyberark/ansible-conjur-collection/blob/main/.github/workflows/ansible-test.yml does not test against the latest version of ansible-core.

**Comment by gotmax23** [comment]
> Note that, if these issues aren't acknowledged within a reasonable time period, the collection may be subject to [removal from Ansible](https://github.com/ansible-collections/overview/blob/main/removal_from_ansible.rst).

https://forum.ansible.com/t/collection-removal-cyberark-conjur/8381 starts the collection removal process

**Comment by gotmax23** [comment]
I updated the issue title accordingly

**Comment by jtuttle** [comment]
@gotmax23 Apologies for the lack of response on this. It has now been brought to my attention and I will get it resolved ASAP.

**Comment by gotmax23** [comment]
Thank you!

**Comment by jtuttle** [comment]
@gotmax23 Do you have a rough date for when we would actually be facing removal? We're working on it, but having a timeline would help me to communicate to my manager the urgency of this work in the face of competing priorities. Thanks!

**Comment by jtuttle** [comment]
@gotmax23 We have pushed a new release that should resolve the compatibility issues. Please let me know if this is sorted. Thanks.

**Comment by jtuttle** [comment]
@gotmax23 Everything look okay?

**Comment by gotmax23** [comment]
HI @jtuttle. Thanks for your quick response, and I apologize for the delay on my end.

https://github.com/ansible-community/package-test-results/blob/main/rendered/11.0.0b1/cyberark.conjur.md are the results for 1.3.1. Some issues still remain.

Regarding the current test failures: I'm not sure what those yaml files are for, but if they're not used by the Ansible code, you can probably ignore those errors (see [Sanity Tests: Ignores](https://docs.ansible.com/ansible/latest/dev_guide/testing/sanity/ignores.html)). `version-added-must-be-major-or-minor` should be addressed also. If that module was legitimately added in a patch release in violation of semver (please do adhere to semver in the future), that can also be added as an ignore.

**Comment by gotmax23** [comment]
https://github.com/cyberark/ansible-conjur-collection/issues/201#issuecomment-2304727205 also should be addressed. Thanks

**Comment by gotmax23** [comment]
Hi, just circling back here. Have you been able to take a look at the sanity test failures?

**Comment by jtuttle** [comment]
Hey @gotmax23, sorry for the delay on this. I have put someone on it who I am confident can wrap things up in the next few weeks so shouldn't be much longer.

**Comment by gl-johnson** [comment]
Hi @gotmax23 - We run the sanity tests in Jenkins interally, but have re-added the GH workflows for better visibility in this public repo. I've updated our test matrix in both instances to include the most recent Ansible versions, and confirmed the latest release passes the sanity tests. Let me know if any other action is needed on our part.

**Comment by jtuttle** [comment]
@gotmax23 Are we okay to close this? AFAIK it has been resolved. Thanks.

**Comment by gotmax23** [comment]
Hi @jtuttle. Yes, it looks like this has been resolved, but please take a look at https://github.com/cyberark/ansible-conjur-collection/issues/210 also. Thanks!
